#!/bin/bash

ASSERTIONS=( Hashmaps.cen "9" "string_keys()"
             Hashmaps.cen "28" "integer_keys()"
             Resizing.cen "5" "read()"
             Resizing.cen "98" "write(98)"
             Resizing.cen "0" "out_of_bounds_read()"
             Resizing.cen "0" "out_of_bounds_write()"
             DynArr.cen "9" "main()"
             Id.cen "3" "id(3)"
             Fibonacci.cen "610" "fib(15)"
             Adder.cen "10" "add(3, 7)"
             Adder.cen "3" "add(1, 2)"
             Branching.cen "3" "main(4)"
             Branching.cen "6" "main(5)"
           )
LEN=${#ASSERTIONS[@]}
